spring.application.name=banco

# Configura��o do H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=http://localhost:8080/h2-console

spring.datasource.url=jdbc:h2:mem:banco_de_usuarios
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=#

# Configura��o do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect